// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'package:platform_image_converter/src/darwin/apple_cf_types.dart'
    as appleCf;
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<__CFAllocator>>()
external final ffi.Pointer<__CFAllocator> kCFAllocatorDefault;

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void CFRelease(ffi.Pointer<ffi.Void> cf);

@ffi.Native<
  CFDictionaryRef Function(
    ffi.Pointer<__CFAllocator>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Long,
    ffi.Pointer<CFDictionaryKeyCallBacks>,
    ffi.Pointer<CFDictionaryValueCallBacks>,
  )
>()
external CFDictionaryRef CFDictionaryCreate(
  ffi.Pointer<__CFAllocator> allocator,
  ffi.Pointer<ffi.Pointer<ffi.Void>> keys,
  ffi.Pointer<ffi.Pointer<ffi.Void>> values,
  int numValues,
  ffi.Pointer<CFDictionaryKeyCallBacks> keyCallBacks,
  ffi.Pointer<CFDictionaryValueCallBacks> valueCallBacks,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(CFDictionaryRef, ffi.Pointer<ffi.Void>)
>()
external ffi.Pointer<ffi.Void> CFDictionaryGetValue(
  CFDictionaryRef theDict,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  CFDataRef Function(
    ffi.Pointer<__CFAllocator>,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Long,
  )
>()
external CFDataRef CFDataCreate(
  ffi.Pointer<__CFAllocator> allocator,
  ffi.Pointer<ffi.UnsignedChar> bytes,
  int length,
);

@ffi.Native<CFMutableDataRef Function(ffi.Pointer<__CFAllocator>, ffi.Long)>()
external CFMutableDataRef CFDataCreateMutable(
  ffi.Pointer<__CFAllocator> allocator,
  int capacity,
);

@ffi.Native<ffi.Long Function(CFDataRef)>()
external int CFDataGetLength(CFDataRef theData);

@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function(CFDataRef)>()
external ffi.Pointer<ffi.UnsignedChar> CFDataGetBytePtr(CFDataRef theData);

@ffi.Native<
  CFStringRef Function(
    ffi.Pointer<__CFAllocator>,
    ffi.Pointer<ffi.Char>,
    ffi.UnsignedInt,
  )
>()
external CFStringRef CFStringCreateWithCString(
  ffi.Pointer<__CFAllocator> alloc,
  ffi.Pointer<ffi.Char> cStr,
  int encoding,
);

@ffi.Native<
  CFNumberRef Function(
    ffi.Pointer<__CFAllocator>,
    ffi.Long,
    ffi.Pointer<ffi.Void>,
  )
>()
external CFNumberRef CFNumberCreate(
  ffi.Pointer<__CFAllocator> allocator,
  int theType,
  ffi.Pointer<ffi.Void> valuePtr,
);

@ffi.Native<
  ffi.UnsignedChar Function(CFNumberRef, ffi.Long, ffi.Pointer<ffi.Void>)
>()
external int CFNumberGetValue(
  CFNumberRef number,
  int theType,
  ffi.Pointer<ffi.Void> valuePtr,
);

@ffi.Native<CFStringRef>()
external CFStringRef kCGColorSpaceSRGB;

@ffi.Native<CGColorSpaceRef Function(CFStringRef)>()
external CGColorSpaceRef CGColorSpaceCreateWithName(CFStringRef name);

@ffi.Native<ffi.Size Function(CGImageRef)>()
external int CGImageGetWidth(CGImageRef image);

@ffi.Native<ffi.Size Function(CGImageRef)>()
external int CGImageGetHeight(CGImageRef image);

@ffi.Native<ffi.Void Function(CGContextRef, appleCf.CGAffineTransform)>()
external void CGContextConcatCTM(
  CGContextRef c,
  appleCf.CGAffineTransform transform,
);

@ffi.Native<ffi.Void Function(CGContextRef, appleCf.CGRect, CGImageRef)>()
external void CGContextDrawImage(
  CGContextRef c,
  appleCf.CGRect rect,
  CGImageRef image,
);

@ffi.Native<ffi.Void Function(CGContextRef, ffi.Int32)>()
external void CGContextSetInterpolationQuality(CGContextRef c, int quality);

@ffi.Native<
  CGContextRef Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    CGColorSpaceRef,
    ffi.Uint32,
  )
>()
external CGContextRef CGBitmapContextCreate(
  ffi.Pointer<ffi.Void> data,
  int width,
  int height,
  int bitsPerComponent,
  int bytesPerRow,
  CGColorSpaceRef space,
  int bitmapInfo,
);

@ffi.Native<CGImageRef Function(CGContextRef)>()
external CGImageRef CGBitmapContextCreateImage(CGContextRef context);

@ffi.Native<CGImageSourceRef Function(CFDataRef, CFDictionaryRef)>()
external CGImageSourceRef CGImageSourceCreateWithData(
  CFDataRef data,
  CFDictionaryRef options,
);

@ffi.Native<
  CFDictionaryRef Function(CGImageSourceRef, ffi.Size, CFDictionaryRef)
>()
external CFDictionaryRef CGImageSourceCopyPropertiesAtIndex(
  CGImageSourceRef isrc,
  int index,
  CFDictionaryRef options,
);

@ffi.Native<CGImageRef Function(CGImageSourceRef, ffi.Size, CFDictionaryRef)>()
external CGImageRef CGImageSourceCreateImageAtIndex(
  CGImageSourceRef isrc,
  int index,
  CFDictionaryRef options,
);

@ffi.Native<CFStringRef>()
external CFStringRef kCGImageDestinationLossyCompressionQuality;

@ffi.Native<
  CGImageDestinationRef Function(
    CFMutableDataRef,
    CFStringRef,
    ffi.Size,
    CFDictionaryRef,
  )
>()
external CGImageDestinationRef CGImageDestinationCreateWithData(
  CFMutableDataRef data,
  CFStringRef type,
  int count,
  CFDictionaryRef options,
);

@ffi.Native<
  ffi.Void Function(CGImageDestinationRef, CGImageRef, CFDictionaryRef)
>()
external void CGImageDestinationAddImage(
  CGImageDestinationRef idst,
  CGImageRef image,
  CFDictionaryRef properties,
);

@ffi.Native<ffi.Bool Function(CGImageDestinationRef)>()
external bool CGImageDestinationFinalize(CGImageDestinationRef idst);

@ffi.Native<CFStringRef>()
external CFStringRef kCGImagePropertyOrientation;

typedef CFStringRef = ffi.Pointer<appleCf.CFString>;

final class __CFAllocator extends ffi.Opaque {}

final class CFDictionaryKeyCallBacks extends ffi.Opaque {}

final class CFDictionaryValueCallBacks extends ffi.Opaque {}

final class __CFDictionary extends ffi.Opaque {}

typedef CFDictionaryRef = ffi.Pointer<__CFDictionary>;

final class __CFData extends ffi.Opaque {}

typedef CFDataRef = ffi.Pointer<__CFData>;
typedef CFMutableDataRef = ffi.Pointer<__CFData>;

final class __CFNumber extends ffi.Opaque {}

typedef CFNumberRef = ffi.Pointer<__CFNumber>;

final class CGImageSource extends ffi.Opaque {}

typedef CGImageSourceRef = ffi.Pointer<CGImageSource>;

final class CGContext extends ffi.Opaque {}

typedef CGContextRef = ffi.Pointer<CGContext>;

final class CGColorSpace extends ffi.Opaque {}

typedef CGColorSpaceRef = ffi.Pointer<CGColorSpace>;

final class CGImage extends ffi.Opaque {}

typedef CGImageRef = ffi.Pointer<CGImage>;

final class CGImageDestination extends ffi.Opaque {}

typedef CGImageDestinationRef = ffi.Pointer<CGImageDestination>;

const int kCFStringEncodingUTF8 = 134217984;

const int kCFNumberFloat64Type = 6;

const int kCFNumberIntType = 9;

const int kCGImageAlphaPremultipliedLast = 1;

const int kCGInterpolationHigh = 3;
