name: Pull Request Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@26fb6927d2874fcc9b3af19cb4cf5cd66ec18a28 # v1.3.0
      - run: flutter analyze
      - run: dart format --output=none --set-exit-if-changed .
